message:
  orderFinish:
    type: 订单
    title: 您的订单已完成
    content: 您的订单 {order_uuid} 已完成，如有问题可在三日内申请售后。
  afterSalesFinish:
    type: 售后
    title: 您的售后订单已完成
    content: 您的售后订单 {order_uuid} 已完成，感谢您的反馈！
  orderSubmit:
    type: 系统
    title: 您有一个新提交的订单待处理
    content: 您有一个新提交的订单 {order_uuid} ，请及时处理！
  afterSalesSubmit:
    type: 系统
    title: 您有一个新的售后订单待处理
    content: 您有一个新的售后订单 {order_uuid} ，请及时处理！